.\" This document is in the public domain.
.\" vim: fdm=marker
.
.\" FRONT MATTER {{{
.Dd Jul 16, 2012
.Os
.Dt PASTISH 1
.
.Sh NAME
.Nm pastish
.Nd Tiny client for SUSE-related pastebin services
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h
.Nm
.Op Fl A Ar API
.Op Fl d Ar DESCRIPTION
.Oo
. Fl o Ar NAME=VALUE
.Oc Ns \&...
.Op Fl s Ar SYNTAX
.Op Fl u Ar USERNAME
.Nm
.Op Fl A Ar API
.Oo
. Fl o Ar NAME=VALUE
.Oc Ns \&...
.Ar ID
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
is a simple client for
.Lk http://pastebin.suse.de
and
.Lk http://susepaste.org.
.Pp
Given a single snippet id,
and possibly the
.Fl A ,
.Fl o
options,
.Nm
will fetch the corresponding snippet, and display it
on standard output.
.Pp
Given no arguments, and possibly any of the
.Fl A, d , o , s , u
options,
.Nm
will upload the contents of standard input,
and display the resulting URL.
.
.Bl -tag -width "xx"
.It Fl h
Display a usage description.
.
.It Fl A Ar API
Server uses
.Ar API
.Pq either Qo int Qc or Qo ext Qc .
.
.It Fl d Ar DESCRIPTION
Submit the snippet with
.Ar DESCRIPTION .
.
.It Fl o Ar NAME=VALUE
Submit or fetch the snippet with form field
.Va NAME
set to
.Va VALUE .
.
.It Fl s Ar SYNTAX
Use
.Ar SYNTAX
for highlighting.
.
.It Fl u Ar USERNAME
The author of the snippet is
.Ar USERNAME .
.
.It Ar ID
Fetch snippet with
.Ar ID .
.El
.
.Pp
.
.Lk http://susepaste.org
snippets are private and expire in 24 hours.
.
.\" DESCRIPTION }}}
.\" .Sh IMPLEMENTATION NOTES
.\" ENVIRONMENT {{{
.Sh ENVIRONMENT
.Nm
itself does not use any environment variables.
It is, however, implemented in terms of third-party commands
which
.Em do
use them.
This means
.Nm
may be influenced by environment variables used by
.Xr zsh 1 ,
.Xr curl 1  ,
possibly others.
.\" ENVIRONMENT }}}
.\" FILES {{{
.Sh FILES
.Nm
reads, in order,
.Pa /etc/pastish
and
.Pa ~/.pastish .
These files, if present, are expected to be
.Xr zsh 1 Ns - Ns compatible
scripts;
they may define any of the following variables:
.
.Bl -tag -width "xx"
.It pastish_api
Either
.Qq Li int
or
.Qq Li ext .
Defaults to
.Qq Li int .
.
.It pastish_server
Defaults to
.Va $pastish_server_int
when
.Va $pastish_api
is
.Qq Li int ,
and
.Va $pastish_server_ext
when
.Va $pastish_api
is
.Qq Li ext .
.
.It pastish_server_int
Defaults to
.Qq Li http://pastebin.suse.de/ .
.
.It pastish_server_ext
Defaults to
.Qq Li http://susepaste.org/ .
.
.It pastish_user
Any string identifying the submitter.
Defaults to
.Qq Va $USER Ns Li @ Ns Va $HOSTNAME ,
with
.Va $USER
defaulting to
.Qq Li anonymous
and
.Va $HOSTNAME
defaulting to
.Qq Li unknown .
.El
.\" FILES }}}
.\" EXAMPLES {{{
.Sh EXAMPLES
.Ss Submit
.Bd -literal
% pastish -s python < ./a-file.py
http://pastebin.suse.de/7890
.Ed
.Ss Display
.Bd -literal
% pastish 7890
if __name__ == '__main__'
  print("Hello world!")
.Ed
.\" EXAMPLES }}}
.\" DIAGNOSTICS {{{
.Sh DIAGNOSTICS
.Ex -std
.\" DIAGNOSTICS }}}
.\" .Sh COMPATIBILITY
.\" SEE ALSO {{{
.Sh SEE ALSO
.Bl
.It
.Lk https://pastebin.suse.de "SUSE pastebin server"
.It
.Lk http://susepaste.org "openSUSE Paste"
.El
.\" SEE ALSO }}}
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" AUTHORS {{{
.Sh AUTHORS
.An Roman Neuhauser Aq Mt rneuhauser@suse.cz
.Lk https://github.com/roman-neuhauser/pastish/
.\" AUTHORS }}}
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/roman-neuhauser/pastish/issues
.\" BUGS }}}
